name: Run migration
concurrency: deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout AREDL Repository
        uses: actions/checkout@v3
        with:
          repository: All-Rated-Extreme-Demon-List/AREDL
          path: './aredl'

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v -o ./backend/ ./...

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 't'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Create pb_data dir
        run: mkdir ./backend/pb_data

      - name: Stop service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo systemctl stop aredl-backend
            while [[ $(systemctl is-active aredl-backend) == "active" ]]; do
              echo "Service is still active. Waiting..."
              sleep 2
            done

      - name: Download db from server
        run: rsync -avz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/pb_data/data.db ./backend/pb_data/data.db

      - name: Start service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: sudo systemctl start aredl-backend

      - name: Run migration
        run: ./backend/AREDL migrate "./aredl/data"

      - name: Stop service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo systemctl stop aredl-backend
            while [[ $(systemctl is-active aredl-backend) == "active" ]]; do
              echo "Service is still active. Waiting..."
              sleep 2
            done

      - name: Upload db to server
        run: rsync -avz ./backend/pb_data/data.db ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/pb_data/data.db

      - name: Start service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: sudo systemctl start aredl-backend
